### ISSUE TITLE
status

### ISSUE THREAD

**Issue by humanitiesNerd** [a-sassmannshausen/guile-config#1]
is this project abandoned ? 

In what state is it ? 
Doesn't work at all ? 

Or does it do anything ?

Could I have an example of a package configured with this ?

Thanks

**Comment by a-sassmannshausen** [comment]
Hi,
I've been working on this behind the scenes over the last year and just pushed significant work which will shortly be released as 0.2.

The API has changed, so if other projects use it they will need to fix the incantations.  From now on the API should be stable.

The repo contains an examples directory, as well as an info manual (that I am still revising for the release).  Together they should be able to give you a good idea of how to use this library.

If you play around with it, do feel free to let me know how you get on — would love the feedback!

Cheers,

Alex
